version: '3.8'

services:
    nginx:
        restart: always
        image: jwilder/nginx-proxy
        container_name: nginx
        depends_on:
            - app
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
            - "/home/whatsapp/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "/etc/nginx/vhost.d"
            - "/usr/share/nginx/html"
            - "/etc/nginx/certs"

    nginx-letsencrypt:
        restart: always
        image: jrcs/letsencrypt-nginx-proxy-companion
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        volumes_from:
            - "nginx"
        
    mongodb:
        container_name: mongodb
        image: mongo:latest
        restart: unless-stopped
        ports:
            - 27017:27017
        volumes:
            - db:/data/db
    app:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - PORT=${PORT}
        depends_on:
            - mongodb
        restart: unless-stopped
        env_file: .env
        ports:
            - ${PORT}:${PORT}
        environment:
            - TOKEN=${TOKEN}
            - PORT=${PORT}
            - MONGODB_ENABLED=${MONGODB_ENABLED}
            - MONGODB_URL=mongodb://mongodb:27017
            - WEBHOOK_ENABLED=${WEBHOOK_ENABLED}
            - WEBHOOK_URL=${WEBHOOK_URL}
            - WEBHOOK_BASE64=${WEBHOOK_BASE64}
            - VIRTUAL_HOST=web.intera.tips
            - LETSENCRYPT_HOST=web.intera.tips
        volumes:
            - ./:/home/node/app
            - /home/node/app/node_modules/

volumes:
    db:
